name = "my-app"
compatibility_date = "2024-08-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNDRlYjJlNDYtYTQ0Yy00ZWU0LTljMzQtZTIwMmZmYjIzZTZkIiwidGVuYW50X2lkIjoiMTNiOTM3Mzg0YzVlYjM4MjZmNTJiOWVmYmY1MmRkY2E0NjdkM2M1ZmM2YjQxY2E0ZWZhOTYyNWFiNTI5ZmI3YiIsImludGVybmFsX3NlY3JldCI6IjE5ZWYxOTQ0LTkwNGYtNDg3OC04NTYxLTBiYWUyODBiNTA2MCJ9.EShTuqRyBZW_NmSmiK0l5hgnZJZMXBkszXvJ7d3_dNc"
JWT_SECRET = "MY_SECRET"